// layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar';
import Footer from './Footer';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <Navbar />
        <div className="flex-grow p-8">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
